### ISSUE TITLE
Stopped working when I died in Mineclonia

### ISSUE THREAD

**Issue by DreamsTandem** [aa6/minetest_wadsprint#9]
My sprint stopped working properly when I got blown up by a creeper after falling underground in a Mineclonia world. Sprint was likely enabled when it happened. I can still turn it "on" and deplete stamina, but it doesn't affect my character's linear running speed anymore. Somehow, my jump height does still change properly.

Closing and reopening the game did nothing to help. Self-destructing in this world never restored it, either. This issue never happened any other time that I died in any world, even while trying to reproduce this problem.

I don't wanna delete my whole world just to get sprinting back. Is there any other fix or at least a workaround for this problem?
[BUGGED.zip](https://github.com/user-attachments/files/16589818/BUGGED.zip)

**Comment by aa6** [comment]
That's a weird issue. The mod stores player stats at `mod_minetest_wadsprint_saved_players_stats.dat` file, so deleting it should be enough to quick fix the problem.

**Comment by aa6** [comment]
However the file seems not to be the issue.

**Comment by DreamsTandem** [comment]
Thank you for the thought, at least. Please let me know if you find anything.

**Comment by aa6** [comment]
The problem was that instead of using `player_monoids`, Mineclonia developers decided to implement their own version of player physics management code. Thus every mod that touches player physics is incompatible with Mineclonia by default and requires additional compatibility code to work properly.

I have just committed a new `minetest_wadsprint` version on github with a compatibility code for Mineclonia. Please download it, put into the minetest mods directory instead of current version and check if that will solve your problem.

If everything will be ok and no new bugs emerge, I will upload new version to the content.minetest.net and then close this issue.

Thank you for reporting the issue.

**Comment by DreamsTandem** [comment]
That seems to have fixed the problem. Thank you for responding so quickly.

**Comment by DreamsTandem** [comment]
Still not sure why it only stopped working after I died that time.
